### ISSUE TITLE
[Not a bug] End of ads can have still image of the product name that has to be skipped

### ISSUE THREAD

**Issue by TheCottonEyeJoe** [0x48piraj/fadblock#161]
This isn't an issue with Fadblock at all, but very often youtube ads after being skipped by Fadblock will still have an image at the end saying the advertiser name with a link to whatever website they are, which cannot be closed unless you press the skip button or wait longer. Is fadblock able to do anything about these, or will I need another extension along with Fadblock in order to keep my interruption from ads to an absolute minimum?

**Comment by TheCottonEyeJoe** [comment]
This is what I mean, in case my words aren't clear:

![Uploading Screenshot 2024-02-02 213546.png…]()

**Comment by 0x48piraj** [comment]
No @TheCottonEyeJoe, it's a known issue and it often happens when there's net interruption or the page loading isn't fast enough.

It's kind of a race condition and solving it requires loads of code and YouTube injects a lot of tracking scripts slowing the user's browser as it is so I have been putting this issue as `wontfix` as of now.

**Comment by TheCottonEyeJoe** [comment]
That's a shame. I can live with it though, it's just a minor annoyance. Thanks for letting me know, at least.
