### ISSUE TITLE
Why are you asking for money if I already sponsored the original FadBlock with you?

### ISSUE THREAD

**Issue by ayylemao** [0x48piraj/fadblock#175]
It gets really annoying since I already sponsored the original FadBlock before you sold it and then made fadblock origin.

**Comment by 0x48piraj** [comment]
Did you not read the email carefully? I spent a hell lot of time and money to recreate the whole database. Just so that the people who supported can get it working again without any hitches.

You don’t have to repay, just login!

If you forgot here’s how, when the payment popup comes, click on “Get license” and then over the window, click Login, put this email of yours, voila - you will be sent a verification link and be logged in!
