### ISSUE TITLE
FadBlock doesn't work when I'm logged in Youtube

### ISSUE THREAD

**Issue by instacart1** [0x48piraj/fadblock#18]
I disabled all adblock plugins and only left FadBlock active while logged in youtube using Chrome, but youtube still blocked videos and said adblock is detected. I switched to incognito mode and only kept FadBlock on (without logging in) and this time it worked.

**Comment by nashworks** [comment]
same - no adblocks but yt stops all videos making it look like i have adblocks but it does not even know which one adblock - it asks me to tell it which adblock i have - but i dont have any adblock - so i had to get fadblock - well well well - it worked on first time chrome reload - then it stopped working and anti adblock from yt started showing up anew - so my question is - how do you get fadblocker work without any excuses - such as hey it works on my end and i dont know what you did - nevertheless can yt simply hold you hostage until you pay them a monthly premium? - is it even legal to excuse you of something that you dont even touch your entire life?

**Comment by 0x48piraj** [comment]
Which browser/platform are you guys using, and can you send a dump of the current DOM state so I can examine closely?

#### How to?
> When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.


A special note to @nashworks: The remark you posted seems like  you're saying "_it should work always-every-single-time without any errors for a lifetime_". What YouTube is doing isn't right and that's why data-privacy advocating people like us build free tools like this one and using these tools comes with associated risks and *some responsibilities*, you know that, right?

**Comment by 0x48piraj** [comment]
Addressed in https://github.com/0x48piraj/fadblock/commit/acb920a8040c1ce2a00c9c147b8307ee19bc6c65. Closing.
