### ISSUE TITLE
Getting ads again on YouTube with Chrome Canary

### ISSUE THREAD

**Issue by CrisWaller1** [0x48piraj/fadblock#187]
I'm getting ads on YouTube with Chrome Canary as of yesterday.

**Comment by Larkspeed** [comment]
As of yesterday you are lucky I have been getting them for days, I'm starting to wonder in this extension is dead.

**Comment by Grg76** [comment]
Do you people in write only mode?  Read this thread: https://github.com/0x48piraj/fadblock/issues/182.

The developer wrote that he is putting out an update, but it takes time to appear in the various browsers. For example, in Firefox it appeared only today, and it works again, it takes 4 days, maybe because of the weekend.

For Chrome teh updates version is V1.1, but i see, that there is still the V1.0, so be patient....

**Comment by 0x48piraj** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/5800726/2fe18e92-0d11-4b29-aaba-3c53342593d6)

I pushed the update a week ago but Chrome has not yet updated the extension. Here's the detailed thread: https://github.com/0x48piraj/fadblock/issues/182

Closing.
