### ISSUE TITLE
Provide credits for chrome background logic

### ISSUE THREAD

**Issue by oddlyspaced** [0x48piraj/fadblock#2]
https://github.com/oddlyspaced/skip/blob/main/background.js

The code is literally the same, down to the logic and method names. I don't have any issues you using my logic, but I would really like to have credits.

**Comment by 0x48piraj** [comment]
Yes, I used your script as a boilerplate but the same code snippet can be found over [YouTube Adblock by Friendly](https://chrome.google.com/webstore/detail/youtube-adblock-by-friend/ehfcoplbhoohillcmlophcfghpeilfjc), [squgeim/yt-ad-autoskipper](https://github.com/squgeim/yt-ad-autoskipper) and over more similar Chrome extensions.

Furthermore, the code didn't work properly because of https://github.com/0x48piraj/fadblock/issues/1. I fixed the script as well as ported it to Opera and Firefox (downgrading to M2). And, the project is less than 24 hours old and I plan to completely rebase the core logic as well as add a small UI. If a project stabilizes and still uses the exact code, then there's a meaning of the credits section. Doesn't it?

**Comment by oddlyspaced** [comment]
> Edit: I can add the credits but I plan to do a rewrite in a day or two so... I will have to remove it afterward, how does that sound?

Sounds fine

**Comment by 0x48piraj** [comment]
The rewrite is complete (https://github.com/0x48piraj/fadblock/commit/2b26707f8c8054a4941ee69ac0757d7955055ca2), and just a small note, in that minuscule script, the only logic was `videoPlayer.currentTime = videoPlayer.duration - [0~2]` which again, is present in numerous YouTube blocking plugins. And if we talk about the code structure, the logic was a bit flawed over a few places i.e. setting up a listener for intrinsic trigger is redundant ([#L46](https://github.com/oddlyspaced/skip/blob/bc7eec30ff636520323e25f11a07ad5fb9abe841/background.js#L46)).

At last, I chose your script as a boilerplate only because you were a colleague back at college and we are connected socially _(for pete's sake!)_.
