### ISSUE TITLE
Worked for a short time, now not working at all.

### ISSUE THREAD

**Issue by menyme** [0x48piraj/fadblock#227]
Blocking ads worked for only a short time.  After that, the time I see an ad became longer and longer, until it stopped working and then YouTube shows its dreaded "Ad blockers violate YouTube's Terms of Service" message.  When that happens, I may have to reload video several times before it plays again, but then the next ad triggers YT's message again.  As of last night, however, fadblock seems to not be working at all because ads are playing in their entirety (or until I hit the "Skip" button).  

It does still seem to work on incognito windows, but when it worked on regular browser windows, it was brilliant.  Please fix it!

**Comment by wesleyhahaha** [comment]
Same here, just can work around a week. Is not working now.

**Comment by Xenirath** [comment]
Also same, used to work flawlessly and now YouTube got to the stage of "will block player after 3 videos" :/

**Comment by brianlevin83** [comment]
Seeing the same issue on my end too, got it working briefly by clearing cache but that only worked for a day or two, still getting constant warning banners as seen above.

**Comment by ckeene159** [comment]
Perhaps others have figured out something that works for them, but here is a suggestion that has worked for us.  Instead of clearing cache each time, if you are running Firefox in Windows you can go to Settings-->Privacy and Security, check box "Delete cookies and site data when Firefox is closed".  Then all we have to do each time is sign in to youtube.

Other browsers may have a similar setting.  This approach works well for us because on this device we use Firefox in Windows only for youtube.  So it doesn't matter if the cookies are always getting cleared out.

Fadblock doesn't work like it used to, though, because now, rather than skipping right over an ad it skips and then stops at a screen where you have to click on "Skip".  Or you can just wait a few seconds and then it goes to another ad.  If you wait on the "skip" screen for that second ad, from our experience, it then goes back to your video.  We usually just click on "skip" on the first ad.

**Comment by SheeepsAreNice** [comment]
That's a useful tip ckeene159, thank you. I use Chrome on desktop only for Youtube and clearing the cache and signing in again with my YouTube-only account is quick and simple to do, solving the problem. Unfortunately, this is all YouTube's deliberate doing as they fight back against adblockers buy constantly fiddling about with their code, yet too many posters here are blaming the author of Fadblock Origin - it's not their fault. They're keeping up as best they can and I salute them for it.

**Comment by 0x48piraj** [comment]
Hello everyone, I hope you’re all doing well. As @ckeene159 mentioned, clearing cookies can be quite helpful but only as a temporary fix.

Life has been tough lately, and it seems the same issue is now affecting my region too, just like many of you. This gives me the opportunity to debug and work towards a solution. I’ve been testing new patches with our internal testers from around the world over email, but progress has been a bit slow. Thank you for your patience.

**Comment by 0x48piraj** [comment]
Hey everyone, I’m currently working on a fix and I’m hopeful that a new version will be released this week!

**Comment by 0x48piraj** [comment]
### Just pushed the new update, 2.0 is coming!

To the loyal existing users, thank you for your support. Simply log in to your accounts, as I have securely migrated all your data, ensuring a seamless transition without the need for account creation or additional payments.

For those who have been using the extension for free, I appreciate your interest in our service. Please note that while you will no longer experience pop-ups, you will need to start a trial account to continue enjoying FadBlock. After the 7-day trial, a lifetime membership will be required to access all features.

Read the [project home](https://github.com/0x48piraj/fadblock) for more information.

Thank you for being part of our journey!

![](https://media.tenor.com/a7vXmLPB_DsAAAAM/ross-rachel.gif)

**Comment by 0x48piraj** [comment]
Let's move here: https://github.com/0x48piraj/fadblock/issues/196
