### ISSUE TITLE
Ads are not skipped anymore

### ISSUE THREAD

**Issue by kevkim12** [0x48piraj/fadblock#30]
Ads are playing as if there are not ad-blocking/ad-skipping extensions

**Comment by 0x48piraj** [comment]
Please include more information so I can investigate. Your browser, platform atleast.

**Comment by kevkim12** [comment]
Google Chrome: Version 118.0.5993.118 (Official Build) (64-bit)
Windows 10 Home, 64-bit operating system, x64-based processor

**Comment by 0x48piraj** [comment]
Can you send me a screenshot of your `chrome://extensions`

**Comment by kevkim12** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/113711991/79fca47b-02e7-44a1-8de2-c2c0bdc8f3f4)

I have disabled uBlock Origin on YouTube. The adblocker worked fine yesterday but it does not seem to be working again.

**Comment by m0lmk** [comment]
Same issue here.

Chrome Version 118.0.5993.118 (Official Build) (64-bit)
Windows 11 Pro Build 22621

uBlock Origin installed but not active on YouTube.

**Comment by 0j-95** [comment]
I have the same problem. I accepted the prompt to udate Fadblock last night and it immediately stopped blocking ads. I don't have any other adblockers running on Youtube. 
I'm using Firefox 119.0 on Windows 10 Pro.

I also get this instead of the scale that used to be there when I click on the extension button in the toolbar. 
![Untitled](https://github.com/0x48piraj/fadblock/assets/149588088/19e0d399-aac4-4584-9fac-a2e779a6a01c)

**Comment by 0x48piraj** [comment]
@m0lmk do you have similar extensions installed?

@0j-95 I am sorry, please uninstall and install the extension again to make it work again.

**Comment by 0x48piraj** [comment]
Fixed. Reference https://github.com/0x48piraj/fadblock/issues/40. Closing.
