### ISSUE TITLE
Mobile version

### ISSUE THREAD

**Issue by lollita** [0x48piraj/fadblock#39]
Youtube mobile version not work in Firefox ?

**Comment by 0x48piraj** [comment]
It was not built for mobiles as most people use the YouTube app or use adblocking tools such as Vanced (now deprecated, look into reVanced if you want a similar solution, I haven't tested it though so exercise caution)

**Comment by hl2jeep** [comment]
> It was not built for mobiles as most people use the YouTube app or use adblocking tools such as Vanced (now deprecated, look into reVanced if you want a similar solution, I haven't tested it though so exercise caution)

https://www.reddit.com/r/revancedapp/comments/xlcny9/revanced_manager_guide_for_dummies/ follow this guide for revanced
i use it on my phone and its pretty foolproof, instead of distributing patched files, it just provides patches you put on the app yourself, so they can't be taken down like vanced did. its unaffected by the current adblock war
