### ISSUE TITLE
Why perm for all the websites

### ISSUE THREAD

**Issue by anotherduckling** [0x48piraj/fadblock#58]
Why do I need to give perm for every website?

### Before
![image](https://github.com/0x48piraj/fadblock/assets/57977673/7c4b7b53-f1f5-426a-805c-b575578ad595)

### After
![image](https://github.com/0x48piraj/fadblock/assets/57977673/fe1d0093-6278-48b6-8f74-107dc156ad22)

<br>

 Also, I didn't understand the payment process thing. Is the extension trial of freemium?

**Comment by 0x48piraj** [comment]
You're correct; it's not ideal. However, for payment gateway access, the extension currently needs to connect with Stripe.com, ExtensionPay, and internal API URLs. I'm planning to update the application to access specific URLs instead of all of them.

The extension is totally free but after 50 ads, it asks for a one-time contribution (works even if you don't want to pay, cancel the popup, refresh the tab).

**Comment by 0x48piraj** [comment]
This was a cop-out for not adding individual URLs, not a good idea, I have urgently pushed 2.1 which addresses this issue.

**Comment by Dooofeee** [comment]
Why do you need to "read and change" our data on extensionpay.com?
