### ISSUE TITLE
About the recent notification for Premium

### ISSUE THREAD

**Issue by JaielZeus** [0x48piraj/fadblock#73]
I get it, everyone wants to make some cash. But going the same path as the advertisers on an **Adblocker** is jsut wrong.

I tell you guys now, if it doesn't change to once a day notification at least, I am just gonna make an adblocker myself for free so everyone can truly be free on youtube.

Horrible experience for me suddenly. I would pay for premium but not if it is so intrusive, sorry. Better pay 12 bucks for yt premium and get rid of the need to have one extension for youtube only than this. Sorry again for the rant, just frustrated a bit!

**Comment by gotexis** [comment]
there is a userscript version available in the repository you can use in userscript plugins (tampermonkey etc.) so you don't hav eto pay

**Comment by JaielZeus** [comment]
I am okay to get 1 notification per day or per update even to remind people to pay for premium. But not on every video. If it goes back to something more sensible I will contribute my part to keep the project running, fine by me.

**Comment by Arcelibs** [comment]
I'm sorry to hear that, perhaps this is where our society lacks progress. You must realize one fact, open source is not free, and Github is not your backyard park. All developers are not free volunteers; everyone has to make a living and has their own jobs. They are not your hired engineers. If you are so unwilling, you can create one yourself or choose to pay for YouTube.

**Comment by 0x48piraj** [comment]
@JaielZeus, I understand your issue and the experience is similar, I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.

Hope you can hold out till then, or disable it until the new version drops.

@gotexis, I see you copt-pasting this over every thread, please read the announcement.

> I genuinely hope you all can appreciate the immense amount of time and effort it requires to sustain a project like this all the while YouTube keeps changing the rules, trying to shut-out everything. All this coupled with working >80 hours/week on my own thing (not FadBlock). If you're not satisfied with the decision where you have to pay a one-time contribution as a gesture for "job well done and keep at it", you still have the option to manually roll back to version 1.3. I won't remove it; it just won't receive further updates. I believe that's a fair compromise.

It's not a hidden thing, the problem is, 1.3 doesn't work with the new YouTube patches but these patches haven't gone global so it may or may not work. If it does and you don't want to wait till I fix the frequency problem, you're free to downgrade manually.

**Comment by Dooofeee** [comment]
Yeah, you're on the verge of being uninstalled man. I might pay but not if you're going to act like a mobile game and ad wall me.

**Comment by Arcelibs** [comment]
> I am okay to get 1 notification per day or per update even to remind people to pay for premium. But not on every video. If it goes back to something more sensible I will contribute my part to keep the project running, fine by me.


This is a joke, especially coming from someone who has never contributed to other projects on Github. Perhaps you should do something first before saying something like this.

**Comment by JaielZeus** [comment]
@0x48piraj Well, I sent 6 bucks your way. Now please keep your word and make it more bearable for the free users of your product.


@Arcelibs Just be quiet honestly if you don't know what people are frustrated about. It was not about getting something for free for me and I have seen your message in which you tried to shame me for it. 

![image](https://github.com/0x48piraj/fadblock/assets/42944799/53531e00-b53e-489e-b014-772ba7246845)

**Comment by Arcelibs** [comment]
> @0x48piraj Well, I sent 6 bucks your way. Now please keep your word and make it more bearable for the free users of your product.
> 
> @Arcelibs Honestly stay out of this if you don't know what people are frustrated about. It was not about getting something for free for me and I have seen your message in which you tried to shame me for it.
> 
> ![image](https://user-images.githubusercontent.com/42944799/280979367-53531e00-b53e-489e-b014-772ba7246845.png)

Alright, I'm sorry. I just wanted to convey that no one seems willing to contribute to this project.

**Comment by JaielZeus** [comment]
> Alright, I'm sorry. I just wanted to convey that no one seems willing to contribute to this project.

All good

**Comment by 0x48piraj** [comment]
I am sorry you guys, it's my fault. The popups are too aggressive. I thought after the initial 500, people would be okay to get popups at a higher rate, but I didn't think that people in the States are getting upwards of 4 ads per video, that's craziness.

As said, I have adjusted the frequency as well as am giving out free licenses to people who can't afford to pay and are reaching out to me. After the adjusted popup rate, I think most people would be ~happy~ more tolerable, I also have adjusted so that you won't have to reload your tab to make it work again. It will run regardless.
