### ISSUE TITLE
Spacebar does not pause video

### ISSUE THREAD

**Issue by JandJplusJ** [0x48piraj/fadblock#76]
Once the pause button is clicked with the mouse, the spacebar no longer pauses the video

**Comment by Grg76** [comment]
I think that is not an issue with Fadblock, i disabled the addon and it changes nothing. I noticed that when i click on the play/pause then a colored frame appears, and as long as this is visible the space bar is not working.  But when i click somewhere else the frame is gone and the spacebar works again.

I don't know if this is an update from Youtube, since i dont pay attention o that so far

![playpause](https://github.com/0x48piraj/fadblock/assets/149167462/b0dc87a2-f531-4430-9f97-b502c48d3374)
