### ISSUE TITLE
Fadblock doesn't work since today Safari

### ISSUE THREAD

**Issue by djgrumpy** [0x48piraj/fadblock#96]
Hey, 
Fadblock stoped blocking YT ads since today! Version 16.1 (18614.2.9.1.12) Safari! 
Is there any fix? 
Every Adblocker is completely uninstalled for the moment! 
Thanks in Advance

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

**Comment by djgrumpy** [comment]
Like I said, I don't use any other adblockers at the moment!

**Comment by harkai84** [comment]
Is there actually a Fadblock version of Safari?

**Comment by 0x48piraj** [comment]
No, there isn't, only an outdated script which I released just because I could. I will suggest you switch to Chrome as FadBlock is most performant there and I don't want to release support for yet another browser (it's gonna come with lots of kinks which will require a lot of work).

I am really sorry :(

Closing this issue.
